### ISSUE TITLE
怎么用dat文件生成datx

### ISSUE THREAD

**Issue by leeyo** [bittopaz/logstash-filter-ipip#1]
怎么用dat文件生成datx？

**Comment by bittopaz** [comment]
没有办法使用dat文件生成datx，这个ip的数据库是用的ipip.net生成的。这种datx格式的数据库是需要付费的，是他们的劳动成果。

**Comment by paulgao** [comment]
我是 IPIP.NET 的创始人，基于该数据是我们团队的劳动成果，和已经在 https://www.ipip.net/faq.html 中明确说明过的情况，请将仓库中的 datx 文件彻底删除，虽然这是个过期文件，但也请务必尊重。
因为找不到您的联系邮件，所以只能在此评论了。
另外，如果您能让代码支持 dat 格式的话，我们和我们的用户都会非常感激，我们也会把这个仓库地址列到第三方支持列表中。
如果有疑问，可以在 QQ 群中与我联系。

**Comment by bittopaz** [comment]
@paulgao  真是抱歉，已经删除了。感谢您的ipip.net，非常棒的IP库。
