### ISSUE TITLE
the exception about the ip is not valid 

### ISSUE THREAD

**Issue by kingloger** [bittopaz/logstash-filter-ipip#2]
if the ip is not valid.the code will still go to ipip_data.each. so it will get exception. so maybe the ipip_data.each need to before the exception for the ip is not valid. like this
    begin
      ip = event[@source]
      ip = ip.first if ip.is_a? Array
      ipip_data =  SM.find_by_ip ip
      event[@target] = {} if event[@target].nil?

```
  ipip_data.each do |key, value|
    event[@target][key.to_s] = value
  end
rescue Exception => e
  @logger.error("Unknown error while looking up IPIP data", :exception => e, :field => @field, :event => event)
end
```

**Comment by bittopaz** [comment]
@kingloger Yes, it makes sense, but in this plugin, it assumes that you have use the correct regex to filter out ip, that means only the correct ip format string can pass to this filter.

If you meet the problem, you might improve your regex in the input plugin, I guess.

**Comment by kingloger** [comment]
yes, a good way.
