### ISSUE TITLE
请问，这个插件已经不支持新的logstash-2.3.1了吗？

### ISSUE THREAD

**Issue by aserunix** [bittopaz/logstash-filter-ipip#3]
logstash-plugin install 虽然已经提示成功，但是logstash-plugin list没有这个插件，logstash-2.3.1/vendor/local_gems/0decb1cf/logstash-filter-ipip-0.1.1下面却没有任何东西，拷贝进去也没用！

../bin/logstash -f logstash_indexer.conf
还是提示
reason=>"Couldn't find any filter plugin named 'ipip'. Are you sure this is correct? Trying to load the ipip filter plugin resulted in this error: no such file to load -- logstash/filters/ipip", :level=>:error

**Comment by bittopaz** [comment]
@aserunix 

logstash-filter-ipip.gemspec 这个文件里面限制了logstash-core的版本:

``` ruby
 s.add_runtime_dependency "logstash-core", '>= 1.4.0', '< 2.0.0'
```

2.3.1的版本我并没有测试过，你可以修改下版本号，然后自己试一下看看，应该没问题。

**Comment by aserunix** [comment]
@bittopaz 谢谢你的答复~
我按正常方法试，发现还是有点问题
**1.    sudo apt-get install -y gem libgemplugin-ruby
2.  sudo gem install rubygems-update
3.  sudo update_rubygems
4.  unzip logstash-filter-ipip-masterr.zip
5.  cd logstash-filter-ipip-master
        vim logstash-filter-ipip.gemspec**

> s.add_runtime_dependency "logstash-core", '>= 2.0.0.beta2', '< 3.0.0'

**6.    gem build logstash-filter-ipip.gemspec （未安装git）**

> logstash-filter-ipip.gemspec:23: command not found: git ls-files
> WARNING:  license value 'Apache License (2.0)' is invalid.  Use a license identifier from
> http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
> Did you mean 'Apache-2.0'?
> WARNING:  prerelease dependency on logstash-core (< 3.0.0, >= 2.0.0.beta2) is not recommended
> WARNING:  open-ended dependency on logstash-devutils (>= 0, development) is not recommended
>   if logstash-devutils is semantically versioned, use:
>     add_development_dependency 'logstash-devutils', '~> 0'
> WARNING:  See http://guides.rubygems.org/specification-reference/ for help
>   Successfully built RubyGem
>   Name: logstash-filter-ipip
>   Version: 0.1.1
>   File: logstash-filter-ipip-0.1.1.gem

**7.    gem build logstash-filter-ipip.gemspec （安装git后,还是报错）**

> fatal: Not a git repository (or any of the parent directories): .git
> WARNING:  license value 'Apache License (2.0)' is invalid.  Use a license identifier from
> http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
> Did you mean 'Apache-2.0'?
> WARNING:  prerelease dependency on logstash-core (< 3.0.0, >= 2.0.0.beta2) is not recommended
> WARNING:  open-ended dependency on logstash-devutils (>= 0, development) is not recommended
>   if logstash-devutils is semantically versioned, use:
>     add_development_dependency 'logstash-devutils', '~> 0'
> WARNING:  See http://guides.rubygems.org/specification-reference/ for help
>   Successfully built RubyGem
>   Name: logstash-filter-ipip
>   Version: 0.1.1
>   File: logstash-filter-ipip-0.1.1.gem

**8.    /usr/local/logstash/bin/logstash-plugin  install logstash-filter-ipip-0.1.1.gem** 

> Validating logstash-filter-ipip-0.1.1.gem
> Installing logstash-filter-ipip
> Installation successful

但是此时/usr/local/logstash/vendor/local_gems/10fe487a/logstash-filter-ipip-0.1.1下没有任何内容

 /usr/local/logstash/Gemfile 文件中有

> gem "logstash-filter-ipip", "0.1.1", :path => "vendor/local_gems/10fe487a/logstash-filter-ipip-0.1.1"
> gem "logstash-filter-geoip2", "0.0.1", :path => "vendor/local_gems/b8346426/logstash-filter-geoip2-0.0.1"
> ...

 /usr/local/logstash/Gemfile.jruby-1.9.lock文件中有

> PATH
>   remote: vendor/local_gems/10fe487a/logstash-filter-ipip-0.1.1
>   specs:
>     logstash-filter-ipip (0.1.1)
> PATH
>   remote: vendor/local_gems/b8346426/logstash-filter-geoip2-0.0.1
>   specs:
>     logstash-filter-geoip2 (0.0.1)
>       logstash-core (>= 2.0.0.beta2, < 3.0.0)
> GEM
>   logstash-filter-geoip2 (= 0.0.1)!
>   logstash-filter-ipip (= 0.1.1)!
> ...

我有尝试手动拷贝logstash-filter-ipip-master下的所有内容到vendor/local_gems/10fe487a/logstash-filter-ipip-0.1.1下，可以启动logstash，但是有问题
filter配置

> \               ipip {
>  \                      source => "remote_addr"
> #                      target => "ipip"
>  \              }

报错：

> fatal: Not a git repository (or any parent up to mount parent )
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> Settings: Default pipeline workers: 24
> Pipeline main started
> Unknown error while looking up IPIP data {
> :exception=>#<Errno::ENOENT: No such file or directory - /data/services/logstash-2.3.1/vendor/local_gems/10fe487a/logstash-filter-ipip-0.1.1/vender/ipip.datx>
> , :field=>nil, :event=>#<LogStash::Event:0x23aa8f62 @metadata_accessors=#<LogStash::Util::Accessors:0x4ca090ca @store={}, @lut={}>, @cancelled=false, @data={"message"=>"xx.xx.xx.159|xx.xx.xx.189|... }
> 
> Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. 
> {"exception"=>#<NoMethodError: undefined method `each' for nil:NilClass>, "backtrace"=>["/data/services/logstash-2.3.1/vendor/local_gems/10fe487a/logstash-filter-ipip-0.1.1/lib/logstash/filters/ipip.rb:179:in `filter'", 
> "/data/services/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-ava/lib/logstash/filters/base.rb:151:in`multi_filter'", 
> "org/jruby/RubyArray.java:1613:in `each'", "/data/services/logstash-.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/filters/base.rb:148:in`multi_filter'", "(eval):98:in `filter_func'", 
> "/data/services/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:267:in`filter_batch'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in`inject'", 
> "/data/services/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:265:in `filter_batch'", 
> "/data/services/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:223:in`worker_loop'",
> "/data/services/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}

**环境：**
ubuntu 12.04
logstash-2.3.1
gem 2.6.6
ruby 1.8.7

**Comment by bittopaz** [comment]
@aserunix 最新的merge #4 之后应该已经支持了，你可以再试试看

**Comment by leeyo** [comment]
@bittopaz 不支持logstash 5吗

**Comment by bittopaz** [comment]
@leeyo 目前还没测试过

**Comment by leeyo** [comment]
@bittopaz 我现在使用在logstash 5.1.1 上面，我改成了读取dat格式的数据。event的操作也有一些调整，event不能直接操作了，需要改成 event.get 和 event.set 

但是偶尔会出现如下错误，比较奇怪的是这些错误不是必现的，有时候启动logstash会出现这些错误，有时候启动完是正常的，看起来和dat的文件读取有关系：
<pre>
[2017-01-06T14:33:23,771][ERROR][logstash.filters.ipip    ] Unknown error while looking up IPIP data {:exception=>#<NoMethodError: undefined method `split' for nil:NilClass>, :field=>"clientip", :ip=>"121.230.72.62", :ipip=>nil, :event=>2017-01-06T06:33:23.670Z beijing-bgp-54.talk-fun.com 121.230.72.62 [06/Jan/2017:14:33:23 +0800] "cid=1325617&xid=2511746&rid=551791&uid=1612334&pid=27&pf=html&type=pause&pl=0&pt=2&bn=0&ba=83&pn=460&ctype=5" "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36" -}

[2017-01-06T14:38:00,616][ERROR][logstash.filters.ipip    ] Unknown error while looking up IPIP data {:exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :field=>"clientip", :ip=>"140.207.185.123", :ipip=>nil, :event=>2017-01-06T06:33:29.680Z beijing-bgp-54.talk-fun.com 140.207.185.123 [06/Jan/2017:14:33:28 +0800] "cid=1361299&xid=3076038&rid=554674&uid=1494490&pid=27&pf=html&type=playing&pl=1&pt=2&bn=1&ba=87&pn=41&ctype=5" "-" "Mozilla/5.0 (Linux; U; Android 5.1.1; zh-cn; OPPO A33 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko)Version/4.0 Chrome/37.0.0.0 MQQBrowser/7.2 Mobile Safari/537.36" 112.109.239.41}

[2017-01-06T14:43:43,954][ERROR][logstash.filters.ipip    ] Unknown error while looking up IPIP data {:exception=>#<ArgumentError: negative length -4 given>, :field=>"clientip", :ip=>"101.39.5.113", :ipip=>nil, :event=>2017-01-06T06:43:43.816Z beijing-bgp-54.talk-fun.com 101.39.5.113 [06/Jan/2017:14:43:43 +0800] "cid=1369622&xid=3498636&rid=562251&uid=1631158&pid=27&pf=android-sdk&type=wait&pl=1&pt=2&bn=0&ba=0&pn=8&ctype=5" "-" "Mozilla/5.0 (Linux; Android 6.0.1; OPPO R9s Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36 MT-ANDROID-SDK-V1.7.4" -}
</pre>

我贴一下完整的代码：
<pre>
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"


module SeventeenMon

  class IPDB

    private_class_method :new

    def ip_db_path
      @ip_db_path ||= ::File.expand_path('../data/17monipdb.dat', ::File.dirname(__FILE__))
    end
    def ip_db
      @ip_db ||= ::File.open ip_db_path, 'rb'
    end

    def offset
      @offset ||= ip_db.read(4).unpack("Nlen")[0]
    end

    def index
      @index ||= ip_db.read(offset - 4)
    end

    def max_comp_length
      @max_comp_length ||= offset - 1028
    end

    def self.instance
      @instance ||= self.send :new
    end

    def seek(_offset, length)
      IO.read(ip_db_path, length, offset + _offset - 1024).split "\t"
    end
  end

  class IP
    attr_reader :ip

    # Initialize IP object
    #
    # == parameters:
    # params::
    #   Might contain address(hostname) and protocol, or just IP
    #
    # == Returns:
    # self
    #
    def initialize(params = {})
      @ip = params[:ip] ||
        Socket.getaddrinfo(params[:address], params[:protocol])[0][3]
    end

    def four_number
      @four_number ||= begin
        fn = ip.split(".").map(&:to_i)
        raise "ip is no valid" if fn.length != 4 || fn.any?{ |d| d < 0 || d > 255}
        fn
      end
    end

    def ip2long
      @ip2long ||= ::IPAddr.new(ip).to_i
    end

    def packed_ip
      @packed_ip ||= [ ip2long ].pack 'N'
    end

    def find
      tmp_offset = four_number[0] * 4
      start = IPDB.instance.index[tmp_offset..(tmp_offset + 3)].unpack("V")[0] * 8 + 1024

      index_offset = nil

      while start < IPDB.instance.max_comp_length
        if IPDB.instance.index[start..(start + 3)] >= packed_ip
          index_offset = "#{IPDB.instance.index[(start + 4)..(start + 6)]}\x0".unpack("V")[0]
          index_length = IPDB.instance.index[(start + 7)].unpack("C")[0]
          break
        end
        start += 8
      end

      return {country: '',province:'',city:'',carrier:''} unless index_offset

      result = IPDB.instance.seek(index_offset, index_length).map do |str|
        str.encode("UTF-8", "UTF-8")
      end

      {
        country: result[0],
        province: result[1],
        city: result[2],
	carrier: result[4]
      }
    end
  end
end

module SeventeenMon
  require "socket"
  require "ipaddr"

  def self.find_by_ip(_ip)
    IP.new(ip: _ip).find
  end
end

SM = SeventeenMon

# This example filter will replace the contents of the default
# message field with whatever you specify in the configuration.
#
# It is only intended to be used as an example.
class LogStash::Filters::IPIP < LogStash::Filters::Base

  # Setting the config_name here is required. This is how you
  # configure this filter from your Logstash config.
  #
  # filter {
  #   ipip {
  #     message => "My message..."
  #   }
  # }
  #
  config_name "ipip"

  # The field containing the IP address to map via ipip.
  config :source, :validate => :string, :require => true

  # An array of geoip fields to be included in the event.
  #
  # Possible fields depend on the database type. By default, all ipip fields
  # are included in the event.
  #
  # For the built-in GeoLiteCity database, the following are available:
  # `city_name`, `continent_code`, `country_code2`, `country_code3`, `country_name`,
  # `dma_code`, `ip`, `latitude`, `longitude`, `postal_code`, `region_name` and `timezone`.
  #config :fields, :validate => :array

  # Specify the field into which Logstash should store the geoip data.
  # This can be useful, for example, if you have `src\_ip` and `dst\_ip` fields and
  # would like the GeoIP information of both IPs.
  #
  # If you save the data to a target field other than `geoip` and want to use the
  # `geo\_point` related functions in Elasticsearch, you need to alter the template
  # provided with the Elasticsearch output and configure the output to use the
  # new template.
  #
  # Even if you don't use the `geo\_point` mapping, the `[target][location]` field
  # is still valid GeoJSON.
  config :target, :validate => :string, :default => 'ipip'


  public
  def register
    #@database = ::Dir.glob(::File.join(::File.expand_path("../../../vendor/", ::File.dirname(__FILE__)),"ipip.datx")).first
    #p @database
    #if !File.exists?(@database)
    #  raise "You must specify 'database => ...' in your geoip filter (I looked for '#{@database}'"
    #end

    #@logger.info("Using geoip database", :path => @database)
  end # def register

  public
  def filter(event)
    return unless filter?(event)
    ipip_data = nil

    begin
      ip = event.get(@source)
      ip = ip.first if ip.is_a? Array
      ipip_data =  SM.find_by_ip ip
    rescue Exception => e
      @logger.error("Unknown error while looking up IPIP data", :exception => e, :field => @source, :ip => ip,:ipip => ipip_data,:event => event)
    end

    event.set(@target,{}) if event.get(@target).nil?

    if ipip_data
	    ipip_data.each do |key, value|
		if value
			event.set("[#{@target}][#{key}]",value)
		end
	    end
    end

    # filter_matched should go in the last line of our successful code
    filter_matched(event)
  end # def filter
end # class LogStash::Filters::IPIP
</pre>
